import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import NavBar from './components/CustomNavBar'
import { ApolloProvider } from './providers/ApolloProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ApolloProvider>
      <ClerkProvider>
        <html lang="en" className="h-full overflow-hidden">
          <body className={inter.className}>
            <NavBar />
            {children}
          </body>
        </html>
      </ClerkProvider>
    </ApolloProvider>
  )
}
